{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (2022.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1752, in print\n",
      "    extend(render(renderable, render_options))\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1390, in render\n",
      "    for render_output in iter_render:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n",
      "    for line in lines:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n",
      "    for segment in segments:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1368, in render\n",
      "    renderable = rich_cast(renderable)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n",
      "    renderable = cast_method()\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n",
      "    pip_cmd = get_best_invocation_for_this_pip()\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n",
      "    if found_executable and os.path.samefile(\n",
      "  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n",
      "    s2 = os.stat(f2)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'\n",
      "Call stack:\n",
      "  File \"/usr/local/bin/pip\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n",
      "    self.handle_pip_version_check(options)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n",
      "    pip_self_version_check(session, options)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n",
      "    logger.info(\"[present-rich] %s\", upgrade_prompt)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: '[present-rich] %s'\n",
      "Arguments: (UpgradePrompt(old='22.1.2', new='24.0'),)\n",
      "Collecting turfpy\n",
      "  Downloading turfpy-0.0.7.tar.gz (37 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting geojson\n",
      "  Downloading geojson-3.1.0-py3-none-any.whl (15 kB)\n",
      "Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from turfpy) (1.22.4)\n",
      "Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from turfpy) (1.8.1)\n",
      "Collecting shapely\n",
      "  Downloading shapely-2.0.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.5/2.5 MB\u001b[0m \u001b[31m4.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m0m\n",
      "\u001b[?25hBuilding wheels for collected packages: turfpy\n",
      "  Building wheel for turfpy (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for turfpy: filename=turfpy-0.0.7-py3-none-any.whl size=39101 sha256=bc5f24adef13c4ff05d877a8246ea9d9319280b0f4094db856df9a69f9442349\n",
      "  Stored in directory: /root/.cache/pip/wheels/f7/f8/07/965ea3fe9ce3d94e9ee6815425f294500adc31eb4c14037c61\n",
      "Successfully built turfpy\n",
      "Installing collected packages: shapely, geojson, turfpy\n",
      "Successfully installed geojson-3.1.0 shapely-2.0.4 turfpy-0.0.7\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1752, in print\n",
      "    extend(render(renderable, render_options))\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1390, in render\n",
      "    for render_output in iter_render:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n",
      "    for line in lines:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n",
      "    for segment in segments:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1368, in render\n",
      "    renderable = rich_cast(renderable)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n",
      "    renderable = cast_method()\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n",
      "    pip_cmd = get_best_invocation_for_this_pip()\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n",
      "    if found_executable and os.path.samefile(\n",
      "  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n",
      "    s2 = os.stat(f2)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'\n",
      "Call stack:\n",
      "  File \"/usr/local/bin/pip\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n",
      "    self.handle_pip_version_check(options)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n",
      "    pip_self_version_check(session, options)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n",
      "    logger.info(\"[present-rich] %s\", upgrade_prompt)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: '[present-rich] %s'\n",
      "Arguments: (UpgradePrompt(old='22.1.2', new='24.0'),)\n",
      "Requirement already satisfied: geojson in /usr/local/lib/python3.8/dist-packages (3.1.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1752, in print\n",
      "    extend(render(renderable, render_options))\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1390, in render\n",
      "    for render_output in iter_render:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n",
      "    for line in lines:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py\", line 245, in split_lines\n",
      "    for segment in segments:\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py\", line 1368, in render\n",
      "    renderable = rich_cast(renderable)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n",
      "    renderable = cast_method()\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n",
      "    pip_cmd = get_best_invocation_for_this_pip()\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n",
      "    if found_executable and os.path.samefile(\n",
      "  File \"/usr/lib/python3.8/genericpath.py\", line 101, in samefile\n",
      "    s2 = os.stat(f2)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'\n",
      "Call stack:\n",
      "  File \"/usr/local/bin/pip\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n",
      "    self.handle_pip_version_check(options)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py\", line 148, in handle_pip_version_check\n",
      "    pip_self_version_check(session, options)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py\", line 237, in pip_self_version_check\n",
      "    logger.info(\"[present-rich] %s\", upgrade_prompt)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1446, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1589, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1599, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1661, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/lib/python3.8/logging/__init__.py\", line 954, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: '[present-rich] %s'\n",
      "Arguments: (UpgradePrompt(old='22.1.2', new='24.0'),)\n"
     ]
    }
   ],
   "source": [
    "!pip install turfpy\n",
    "!pip install geojson"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import json\n",
    "import time\n",
    "import socket\n",
    "import uuid\n",
    "import random\n",
    "from datetime import datetime\n",
    "import pytz\n",
    "from turfpy.measurement import bbox, boolean_point_in_polygon\n",
    "from geojson import Feature, Point, Polygon, MultiPolygon\n",
    "\n",
    "# Cargar el GeoJSON de Medellín\n",
    "with open('medellin.json', 'r') as f:\n",
    "    medellin = json.load(f)\n",
    "    \n",
    "# Cargar el GeoJSON de las comunas y corregimientos\n",
    "with open('barrios.json', 'r') as f:\n",
    "    barrios = json.load(f)\n",
    "\n",
    "box = bbox(medellin[\"features\"][0][\"geometry\"])\n",
    "\n",
    "# Definir las coordenadas aproximadas de Medellín\n",
    "lat_range = (box[1], box[3])  # Latitud de Medellín\n",
    "lng_range = (box[0], box[2])  # Longitud de Medellín\n",
    "\n",
    "\n",
    "# Generar un punto aleatorio\n",
    "def generate_point():\n",
    "    while(True):\n",
    "        lat_rand = round(random.uniform(*lat_range), 6)\n",
    "        lng_rand = round(random.uniform(*lng_range), 6)\n",
    "        point = Feature(geometry=Point([lng_rand, lat_rand]))\n",
    "        polygons = [feature[\"geometry\"][\"coordinates\"] for feature in barrios[\"features\"]]\n",
    "        multi_polygon = MultiPolygon(polygons)\n",
    "        if boolean_point_in_polygon(point, multi_polygon):\n",
    "            return lat_rand, lng_rand\n",
    "\n",
    "# Generar datos simulados\n",
    "def generate_event():\n",
    "    lat, lng = generate_point()\n",
    "    event = {\n",
    "        \"latitude\": lat,\n",
    "        \"longitude\": lng,\n",
    "        \"date\": datetime.now(pytz.timezone('America/Bogota')).strftime(\"%d/%m/%Y %H:%M:%S\"),\n",
    "        \"customer_id\": random.randint(1000, 2000),\n",
    "        \"employee_id\": random.randint(9000, 9040),\n",
    "        \"quantity_products\": random.randint(10, 50),\n",
    "        \"order_id\": str(uuid.uuid4()),\n",
    "        # \"commune\": random.choice(comunas),\n",
    "        # \"neighborhood\": random.choice(barrios),\n",
    "        # \"partition_date\": datetime.now().strftime(\"%d%m%Y\"),\n",
    "        # \"event_date\": datetime.now().strftime(\"%d/%m/%Y %H:%M:%S\"),\n",
    "        # \"event_day\": datetime.now().day,\n",
    "        # \"event_hour\": datetime.now().hour,\n",
    "        # \"event_minute\": datetime.now().minute,\n",
    "        # \"event_month\": datetime.now().month,\n",
    "        # \"event_second\": datetime.now().second,\n",
    "        # \"event_year\": datetime.now().year\n",
    "    }\n",
    "    return event\n",
    "\n",
    "def send_data(s, conn, data):\n",
    "    conn.sendall(json.dumps(data).encode() + b'\\n')\n",
    "    print(\"enviado:\", data)\n",
    "    \n",
    "\n",
    "def generate_data(host, port, interval):\n",
    "\n",
    "    s = socket.socket()\n",
    "    s.bind((host, port))\n",
    "    s.listen(1)\n",
    "    print(f\"Listening on {host}:{port}\")\n",
    "\n",
    "    conn, addr = s.accept()\n",
    "    print(f\"Connection from {addr}\")\n",
    "    try:\n",
    "        while True:\n",
    "            event = generate_event()\n",
    "            # Esperar 30 segundos antes de generar el siguiente evento\n",
    "            send_data(s, conn, event)\n",
    "            # Ejemplo de guardado en un archivo JSON\n",
    "            with open('simulated_data.json', 'a') as file:\n",
    "                file.write(json.dumps(event) + \"\\n\")\n",
    "            \n",
    "            time.sleep(interval)\n",
    "            \n",
    "    except KeyboardInterrupt:\n",
    "        print(\"Deteniendo el servidor...\")\n",
    "        conn.close()\n",
    "        s.close()\n",
    "        print(\"Conexión cerrada.\")\n",
    "    \n",
    "    except BrokenPipeError:\n",
    "        print(\"La conexión ha sido cerrada.\")\n",
    "        conn.close()\n",
    "        s.close()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Listening on localhost:4224\n",
      "Connection from ('127.0.0.1', 35722)\n",
      "enviado: {'latitude': 6.173934, 'longitude': -75.663362, 'date': '12/06/2024 12:28:42', 'customer_id': 1248, 'employee_id': 9019, 'quantity_products': 18, 'order_id': '06059f9e-43db-4e75-bf61-d50e2386ed7e'}\n",
      "enviado: {'latitude': 6.248289, 'longitude': -75.70486, 'date': '12/06/2024 12:28:43', 'customer_id': 1636, 'employee_id': 9024, 'quantity_products': 12, 'order_id': '62adfc9b-3d4e-420c-9b65-9bfc22d762a6'}\n",
      "enviado: {'latitude': 6.192264, 'longitude': -75.632434, 'date': '12/06/2024 12:28:45', 'customer_id': 1214, 'employee_id': 9034, 'quantity_products': 14, 'order_id': '2f7045e2-86aa-48fe-a691-73d96d251331'}\n",
      "enviado: {'latitude': 6.244756, 'longitude': -75.679238, 'date': '12/06/2024 12:28:47', 'customer_id': 1536, 'employee_id': 9030, 'quantity_products': 14, 'order_id': '4910beee-d489-4cd8-9b1b-98ba918c2e35'}\n",
      "enviado: {'latitude': 6.240215, 'longitude': -75.63636, 'date': '12/06/2024 12:28:49', 'customer_id': 1636, 'employee_id': 9020, 'quantity_products': 31, 'order_id': '2395452d-53dc-420a-9479-c1a3dd0d5089'}\n",
      "enviado: {'latitude': 6.252732, 'longitude': -75.516288, 'date': '12/06/2024 12:28:50', 'customer_id': 1678, 'employee_id': 9008, 'quantity_products': 39, 'order_id': '06484fe6-171d-46eb-a157-a5a88e887e53'}\n",
      "enviado: {'latitude': 6.228609, 'longitude': -75.675556, 'date': '12/06/2024 12:28:52', 'customer_id': 1147, 'employee_id': 9016, 'quantity_products': 37, 'order_id': 'f7c655fa-a35c-4be9-8659-65e3ee207955'}\n",
      "enviado: {'latitude': 6.19389, 'longitude': -75.638417, 'date': '12/06/2024 12:28:54', 'customer_id': 1117, 'employee_id': 9033, 'quantity_products': 45, 'order_id': '6b620484-4abc-48ac-81e9-4f5bf47a7ba5'}\n",
      "enviado: {'latitude': 6.256292, 'longitude': -75.55306, 'date': '12/06/2024 12:28:56', 'customer_id': 1203, 'employee_id': 9004, 'quantity_products': 42, 'order_id': '0096f2a0-01af-4909-b67f-1a035de2b0c9'}\n",
      "enviado: {'latitude': 6.190177, 'longitude': -75.499403, 'date': '12/06/2024 12:28:57', 'customer_id': 1091, 'employee_id': 9035, 'quantity_products': 17, 'order_id': 'cc3505b9-9091-4183-b8a7-25c2e84fa8be'}\n",
      "enviado: {'latitude': 6.250693, 'longitude': -75.539998, 'date': '12/06/2024 12:28:59', 'customer_id': 1811, 'employee_id': 9037, 'quantity_products': 12, 'order_id': '8adbefe9-75ed-4d0b-a103-9139b0cbb80c'}\n",
      "enviado: {'latitude': 6.239094, 'longitude': -75.698232, 'date': '12/06/2024 12:29:01', 'customer_id': 1563, 'employee_id': 9037, 'quantity_products': 30, 'order_id': 'e7c8123a-0f50-4abc-acd8-405a34cfe3c3'}\n",
      "enviado: {'latitude': 6.176209, 'longitude': -75.536434, 'date': '12/06/2024 12:29:03', 'customer_id': 1023, 'employee_id': 9020, 'quantity_products': 41, 'order_id': '7bef8817-f2ca-4d9f-872a-5cc76155e597'}\n",
      "enviado: {'latitude': 6.251901, 'longitude': -75.695936, 'date': '12/06/2024 12:29:05', 'customer_id': 1589, 'employee_id': 9033, 'quantity_products': 50, 'order_id': '659581db-7ed1-467b-bc1d-0c58389b3fc4'}\n",
      "enviado: {'latitude': 6.289458, 'longitude': -75.536082, 'date': '12/06/2024 12:29:06', 'customer_id': 1745, 'employee_id': 9036, 'quantity_products': 48, 'order_id': '2059058e-6e3d-4b17-9ab6-19e7f8130272'}\n",
      "enviado: {'latitude': 6.352362, 'longitude': -75.664045, 'date': '12/06/2024 12:29:08', 'customer_id': 1331, 'employee_id': 9026, 'quantity_products': 35, 'order_id': '3706083c-af5d-45ca-bd96-137c92d796cf'}\n",
      "enviado: {'latitude': 6.219068, 'longitude': -75.627463, 'date': '12/06/2024 12:29:10', 'customer_id': 1485, 'employee_id': 9010, 'quantity_products': 47, 'order_id': '20490545-508a-4618-a4ec-f04860ceb905'}\n",
      "enviado: {'latitude': 6.218089, 'longitude': -75.544205, 'date': '12/06/2024 12:29:14', 'customer_id': 1083, 'employee_id': 9018, 'quantity_products': 47, 'order_id': 'c7b88444-e452-4493-b4ff-b7f63888cab1'}\n",
      "enviado: {'latitude': 6.207562, 'longitude': -75.659084, 'date': '12/06/2024 12:29:15', 'customer_id': 1212, 'employee_id': 9038, 'quantity_products': 32, 'order_id': '9704187c-3e00-4132-a0ee-7b794d071810'}\n",
      "enviado: {'latitude': 6.239512, 'longitude': -75.574827, 'date': '12/06/2024 12:29:17', 'customer_id': 1085, 'employee_id': 9011, 'quantity_products': 33, 'order_id': '44f92f72-1677-4732-a187-bc9c1c03f641'}\n",
      "enviado: {'latitude': 6.264096, 'longitude': -75.540915, 'date': '12/06/2024 12:29:19', 'customer_id': 1073, 'employee_id': 9026, 'quantity_products': 28, 'order_id': '6e1ea26b-dddb-43c7-86f6-1bacc55eaf19'}\n",
      "Deteniendo el servidor...\n",
      "Conexión cerrada.\n"
     ]
    }
   ],
   "source": [
    "# generate_data(host, port, interval_in_seconds)\n",
    "generate_data('localhost', 4224, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
